### ISSUE TITLE
[BUG]  Erro ao iniciar o modpack pelo TLauncher

### ISSUE THREAD

**Issue by Frotas** [CraftGXNetwork/UltraPack#7]
Após realizar o download e a extração do arquivo ZIP disponibilizado na pagina de releases do GitHub através deste [link](https://github.com/CraftGXNetwork/UltraPack/releases/tag/TLauncher).

![image](https://user-images.githubusercontent.com/89676387/210889286-a842f6d9-3cc6-4c70-8fc7-dfdebf1b6879.png)
> Imagem do erro emitido pelo launcher.

Arquivo de log: [tl.console.log](https://github.com/CraftGXNetwork/UltraPack/files/10356090/tl.console.log)
> Link do arquivo de log criado pelo launcher.

Desde já agradeço a atenção.

**Comment by iagothz** [comment]
Troca o "Versão UltraPack" por "Forge 1.16.5"
